import java.sql.Date;
import java.util.Random;

import org.hibernate.Session;
import org.shreejalarammandir.model.mandirpeople.CommitteeMember;
import org.shreejalarammandir.model.mandirpeople.FullName;
import org.shreejalarammandir.model.mandirpeople.Mahraj;
import org.shreejalarammandir.model.mandirpeople.MandirPeople;
import org.shreejalarammandir.model.mandirpeople.Post;
import org.shreejalarammandir.model.mandirpeople.ServicesGroup;
import org.shreejalarammandir.model.mandirpeople.VolunteerService;

class Populate {
	
	static void populate(Session session) {

		// make Chairman Post
		Post post = new Post();
		post.setTitle("Chairman");
		session.save(post);
		
		// populate MandirPeople: Chairman
		PopulateChairman.populateChairman(session);
		
		// populate 150 ServicesGroup - backend 											(must have VolunteerService)
		// populate 150 VolunteerService - backend											(must have ServicesGroup)
		PopulateSGandVS.populateSGandVS(session);
		
		// populate 2 Mahraj - frontend
		PopulateMahraj.populateMahraj(session);
		
		// populate 150 Post - backend ( should have CommitteeMember )
		PopulatePost.populatePost(session);
		// populate 150 Authority - developer ( should have Post and MandirPeople )
		PopulateAuthority.populateAuthority(session);
		// populate 150 CommitteeMember - BACKend											(must have a post)
		PopulateCommitteeMember.populateCommitteeMember(session);
		
		
		// populate 150 FullName - AutoGenerated
		String[][] name = PopulateFullName.populateFullNames();
		// populate 150 Volunteer - frontend												(must have VolunteerService)
		PopulateVolunteer.populateVolunteer(name, session);


		// populate Pooja - backend 														(must have MandirPeople(contactUs))
		// populate PoojaNote - backend 													(must have Pooja )
		PopulatePandPN.populatePandPN(session);
		
		// '''''''''''TOGETHER'''''''''''
		// populate 300 Event - backend 													(must have Venue, DayOfEvent, ContactUs)
		// populate 300 DayOfEvent - backend 												(must have Event, Program)
		// populate 300 Program - backend 													(must have DayOfEvent)
		// populate 300 Venue - backend 													(must have event/activity)
		// populate 300 Seva - backend 														(must have Event)
		// populate 300 Sponsorship - backend 												(must have Event)
		// populate 300 Ticket - backend 													(must have Event)
		// populate 300 EventNote - backend 												(must have Event)
		// populate 300 EventFlyerUrl - backend 											(must have Event)
		// populate 300 EventButton - backend 												(must have Program)
		// populate 300 EventPicUrl - backend 												(must have Event)
		PopulateEvent.populateEvent(session);
		// '''''''''''TOGETHER'''''''''''
		
		// '''''''''''TOGETHER'''''''''''
		// populate 300 Activity - backend 													(must have Venue, ContactUs)
		// populate 150 Session - backend 													(must have Activity)
		// populate 150 WeekOfMonth - backend 												(must have Session)
		// populate 150 SessionNote - backend 												(must have Session)
		// populate 150 SessionButton - backend 											(must have Session)
		// populate 150 ActivityPicUrl - backend 											(must have Activity)
		PopulateActivity.populateActivity(session);
		// '''''''''''TOGETHER'''''''''''


		// '''''''''''TOGETHER'''''''''''
		// populate 150 Lesson - AutoGenerated												(must have MandirPeople)
		// populate 150 ActivityLesson - backend 											(must have Activity)
		// populate 150 EventLesson - backend 												(must have Event)
		// populate 150 GeneralLesson - backend
		PopulateLesson.populateLesson(session);
		
		// '''''''''''TOGETHER'''''''''''

		// populate 150 Gujarati Calender - backend
		PopulateGujaratiCalender.populateGujaratiCalender(session);
		
		// populate 150 Subscriber - frontend
		PopulateSubscriber.populateSubscriber(session);

		// populate 150 Parcha - frontend
		PopulateParcha.populateParcha(session);

		// populate 150 Publication - backend (should have Parcha)
		PopulatePublication.populatePublication(session);
	}

}
