spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:h2:mem:sjmtest;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;INIT=CREATE SCHEMA IF NOT EXISTS sjm
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
mandir.google-calendar.enabled=false
mandir.google-calendar.calendar-id=test-calendar-id
